//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.3053
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("www.devage.com")]
[assembly: AssemblyProduct("dotNetInstaller")]
[assembly: AssemblyCopyright("Copyright (c) www.devage.com 2008")]
[assembly: AssemblyTrademark("All Rights Reserved")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyVersion("1.5.94.0")]
[assembly: AssemblyFileVersion("1.5.94.0")]


