#pragma once

#define VERSION_MAJOR                 1
#define VERSION_MINOR                 4
#define VERSION_BUILD                 31
#define VERSION_REVISION              1749

#define VERSION_BUILDTIME             1749

#define VERSION_PRODUCTNAME_VALUE     "dotNetInstaller"
#define VERSION_COMPANYNAME_VALUE     "www.devage.com"
#define VERSION_LEGALCOPYRIGHT_VALUE  "Copyright (c) Davide Icardi, Matthias Jentsch (www.devage.com) 2008"
#define VERSION_LEGALTRADEMARK_VALUE  "All Rights Reserved"

#define PRODUCT_VERSION VERSION_MAJOR,VERSION_MINOR,VERSION_BUILD,VERSION_REVISION
#define BINARY_VERSION VERSION_MAJOR,VERSION_MINOR,VERSION_BUILD,VERSION_BUILDTIME

#define VERSION__STR2__(x) #x
#define VERSION__STR1__(x) VERSION__STR2__(x)

#define PRODUCT_VERSION_VALUE  VERSION__STR1__(PRODUCT_VERSION)
#define BINARY_VERSION_VALUE  VERSION__STR1__(BINARY_VERSION)

#define VERSION_FILEVERSION           BINARY_VERSION
#define VERSION_PRODUCTVERSION        PRODUCT_VERSION
#define VERSION_FILEVERSION_VALUE     BINARY_VERSION_VALUE
#define VERSION_PRODUCTVERSION_VALUE  PRODUCT_VERSION_VALUE
#pragma once

#define VERSION_MAJOR                 1
#define VERSION_MINOR                 4
#define VERSION_BUILD                 31
#define VERSION_REVISION              1749

#define VERSION_BUILDTIME             1749

#define VERSION_PRODUCTNAME_VALUE     "dotNetInstaller"
#define VERSION_COMPANYNAME_VALUE     "www.devage.com"
#define VERSION_LEGALCOPYRIGHT_VALUE  "Copyright (c) Davide Icardi, Matthias Jentsch (www.devage.com) 2008"
#define VERSION_LEGALTRADEMARK_VALUE  "All Rights Reserved"

#define PRODUCT_VERSION VERSION_MAJOR,VERSION_MINOR,VERSION_BUILD,VERSION_REVISION
#define BINARY_VERSION VERSION_MAJOR,VERSION_MINOR,VERSION_BUILD,VERSION_BUILDTIME

#define VERSION__STR2__(x) #x
#define VERSION__STR1__(x) VERSION__STR2__(x)

#define PRODUCT_VERSION_VALUE  VERSION__STR1__(PRODUCT_VERSION)
#define BINARY_VERSION_VALUE  VERSION__STR1__(BINARY_VERSION)

#define VERSION_FILEVERSION           BINARY_VERSION
#define VERSION_PRODUCTVERSION        PRODUCT_VERSION
#define VERSION_FILEVERSION_VALUE     BINARY_VERSION_VALUE
#define VERSION_PRODUCTVERSION_VALUE  PRODUCT_VERSION_VALUE
